<a href="https://colab.research.google.com/github/20241984/Ejercicios/blob/main/Distance_and_time_Starter_Code_Diego_Reyes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Starter Code

# Exploring NumPy Arrays: Distance and Time

1) Import the numpy library

In [45]:
import numpy as np

2) Create a numpy array called "distance" that includes the following distances (in meters): 100, 200, 400, 800, 1500, 3000, 5000, 10000

In [46]:
distance = [100,200,400,800,1500,3000,5000,10000]
type(distance)
distance_array = np.array(distance)
distance_array


array([  100,   200,   400,   800,  1500,  3000,  5000, 10000])

3) Use the np.min() and np.max() functions to find the minimum and maximum distances

In [47]:
A= np.min(distance_array)
print(A)
B= np.max(distance_array)
print(B)


100
10000


4) To find the average distance, use the np.mean() function

In [48]:
np.mean(distance_array)


2625.0

5) use the np.sum() function to find the total distance

In [49]:
np.sum(distance_array)

21000

6) Another valuable function is the np.cumsum() function which outputs the cumulative sum...notice the output will be 100, 300, 700 as it adds each new distance

In [50]:
np.cumsum(distance_array)


array([  100,   300,   700,  1500,  3000,  6000, 11000, 21000])

7) To round all of the values in an array, use np.round()

In [51]:
np.round(distance_array)

array([  100,   200,   400,   800,  1500,  3000,  5000, 10000])

8) Create a numpy array called time that includes the following times (in seconds):  10.62, 21.34, 48.25, 113.43, 233.96, 506.53, 866.17, 1757.45

In [52]:
time = [10.62, 21.34, 48.25, 113.43, 233.96, 506.53, 866.17, 1757.45]
tiempo_array =np.array(time)
tiempo_array

array([  10.62,   21.34,   48.25,  113.43,  233.96,  506.53,  866.17,
       1757.45])

9) the values in your time array correspond to olympic records for running the corresponding distances.  Perform the calculation needed to find the speed (in m/s) for each record distance.  Note that speed is distance divided by time.

In [53]:
distance_array.dtype
tiempo_array.dtype
metros_xseg = distance_array / tiempo_array
metros_xseg


array([9.41619586, 9.37207123, 8.29015544, 7.0528079 , 6.41135237,
       5.92265019, 5.77253888, 5.69006231])

10) One common problem data scientists run into is that we are given information in units that are not consistent.  
For example, we might want to compare data that is given in meters to second to data that is given in miles per hour. A cheetah is the fastest land animal which can reach speeds of 75.0 miles per hour.  
In order to compare our olympians to a cheetah, we need to be able to convert from one unit to another.
Perform calculations to convert the olympic record speeds from meters/second into miles per hour.  Note: 1 meter = 0.00062 miles

How do our olympians compare to the cheetah?

(Hint: Speed in m/s multiplied by 0.00062 and multiplied by 3600 will give speed in miles per hour)

In [54]:
distance_array
distance_millas = distance_array
distance_millas
convert_mill = 0.00062
n = 0
for n in range(len(distance_array)):
      distance_millas[n] =distance_array[n]*convert_mill
distance_array

array([0, 0, 0, 0, 0, 1, 3, 6])

In [58]:
# Arreglo de tiempo
tiempo_array
tiempo_horas = tiempo_array
M = 0
for m in range(len(tiempo_horas)):
      tiempo_horas[m] = tiempo_horas[m]*3600
tiempo_horas
millas_per_hora = distance_millas / tiempo_horas
millas_per_hora


array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 4.23143160e-14, 7.42353251e-14, 7.31746696e-14])