<a href="https://colab.research.google.com/github/20241984/Ejercicios/blob/main/Panaderia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Imports

In [105]:
import numpy as np


In [106]:
# Lista de precio de pasteles: Brownie, Galletas, Pastel
price = [2,1,10]
type(price)

# Cantidades Vendidas
quantity_sold = [17,40,1]
type(quantity_sold)


list

In [107]:
# transformamos las lista en array con la biblioteca numpy
# Ingresos por venta
price_array = np.array(price)
quantity_sold_array = np.array(quantity_sold)
price_array*quantity_sold
venta = sum(price_array*quantity_sold)
print(price_array*quantity_sold)
venta

[34 40 10]


84

In [108]:
# Costo de Fabricacion
cost_array= np.array([0.25,0.5,5.0])
# Ganancia
Profit_array = price_array-cost_array
print(Profit_array)
# Supongamos que quieren identificar qué elementos obtuvieron un beneficio superior a $2 por elemento.
Profit_array>2

[1.75 0.5  5.  ]


array([False, False,  True])

In [109]:
#Esperen! ¡Este no es el resultado que queríamos! El array de NumPy hizo lo mejor que sabe hacer:
# añadió un siete a *cada elemento* en el array.  Para regresar a los valores originales, restaremos 7,
# luego usaremos la función np.append() para incluir el valor 7 como se desee.
price_array = price_array + [7]
print(price_array)
price_array = price_array - [7]
print(price_array)
# Se agrega nuevo producto torta a precio de 7
# Con la funcion np.append se agrega una elemento mas
price_array = np.append(price_array, 7)
print(price_array)


[ 9  8 17]
[ 2  1 10]
[ 2  1 10  7]


In [110]:
# Se agregar precios 4,50 dulces, 3 magdalena, 4 barra de pan de plátano y 9  torta
price_array = np.append(price_array, [4.5,3,4,9])
print(price_array)

[ 2.   1.  10.   7.   4.5  3.   4.   9. ]


In [111]:
#Para comprobar el tipo de datos de los elementos del array, pueden utilizar lo siguiente:
price_array.dtype

dtype('float64')

In [112]:
# eliminar el elemento en el índice 7
# recuerden usar indexación cero, o como es el último elemento
# podemos ir por la derecha y utilizar el elemento -1.
price_array = np.delete(price_array,-1)
print(price_array)

[ 2.   1.  10.   7.   4.5  3.   4. ]


In [113]:
# Reemplazar
# Después el club decide subir el precio de los pasteles de $10 a $12.
# Nuevamente, tendremos que identificar el elemento usando el índice.
# Los pasteles están en el índice 2.
price_array[2] = 12
print(price_array)


[ 2.   1.  12.   7.   4.5  3.   4. ]


In [114]:
# Actualicen el quantity_sold_array para incluir la venta de 2 tartas,
# 3 bandejas de dulces, 16 magdalenas y 5 panes de plátano.
quantity_sold_array = np.array(quantity_sold)
quantity_sold_array = np.append(quantity_sold,[2,3,16,5])
quantity_sold_array
# También se darán cuenta que una de las galletas que pensaron que se había vendido en realidad se cayó al suelo,
# así que editen quantity_sold_array de 40 a 39
quantity_sold_array [1]= 39
# ingreso por venta
quantity_sold_array*price_array



array([34. , 39. , 12. , 14. , 13.5, 48. , 20. ])

In [117]:
# reen un array de NumPy "quantity_leftover" que incluya la cantidad de cada elemento
# restante al final de la venta: 2 pasteles, 1 tarta, 6 bandejas de dulces, 2 panes de plátano.
# Pista: Asegúrense de incluir “0” de cada elemento que se haya vendido.
# ¿Por qué esto es importante cuando se crea un array?
quantity_leftover= [0,0,2,1,6,0,2]
quantity_leftover_array = np.array(quantity_leftover)
quantity_leftover_array
# el Club vende a mitar de precios los salos
venta_liq = sum(quantity_leftover_array*price_array)
venta_liq = venta_liq/2
venta_liq


33.0

In [120]:
# ingreso totales
venta_normal = sum(price_array * quantity_sold_array)
venta_normal
ingreso_tot = venta_normal.sum()+venta_liq.sum()
ingreso_tot



213.5